<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260306203000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create access_token_blacklist table to enforce JWT + HttpOnly cookie pairing.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE access_token_blacklist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, reason VARCHAR(80) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2EAB6D95F1BC6A09 ON access_token_blacklist (token_hash)');
        $this->addSql('CREATE INDEX idx_access_token_blacklist_expires ON access_token_blacklist (expires_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE access_token_blacklist');
    }
}
