<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260317235500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remove app_task, remove github_repository_name e adiciona repositórios ignorados em ui_settings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE ui_settings ADD ignored_repository_keys JSON DEFAULT '[]' NOT NULL");
        $this->addSql('ALTER TABLE app_user DROP COLUMN github_repository_name');
        $this->addSql('ALTER TABLE app_task DROP CONSTRAINT FK_8D12FF38A76ED395');
        $this->addSql('DROP TABLE app_task');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE app_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, title VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, completed BOOLEAN DEFAULT FALSE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_app_task_owner ON app_task (owner_id)');
        $this->addSql('CREATE INDEX idx_app_task_created ON app_task (created_at)');
        $this->addSql('ALTER TABLE app_task ADD CONSTRAINT FK_8D12FF38A76ED395 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE app_user ADD github_repository_name VARCHAR(191) DEFAULT NULL');
        $this->addSql('ALTER TABLE ui_settings DROP ignored_repository_keys');
    }
}
