framework:
    cache:
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            access_token_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
