export const navigationItems = [
  {
    key: 'dashboard',
    short: 'DB',
    label: 'Dashboard',
    description: 'Graficos e analises operacionais',
    eyebrow: '',
    title: 'Dashboard',
    descriptionLong: '',
  },
  {
    key: 'tasks',
    short: 'TF',
    label: 'Tarefas',
    description: 'Issues atribuidas ou backlog completo do repositorio',
    eyebrow: 'Issues do GitHub',
    title: 'Inbox operacional do OctoFlow',
    descriptionLong: 'Alterne entre suas issues atribuidas e todas as issues do repositorio, com troca rapida entre repositorios acessiveis.',
  },
  {
    key: 'finance',
    short: 'FN',
    label: 'Financeiro',
    description: 'Lançamentos, recorrência, investimentos e exportações',
    eyebrow: 'Financeiro',
    title: 'Controle financeiro pessoal',
    descriptionLong: 'Gerencie contas a pagar e receber, parcelamentos, simulações e exportações do fluxo financeiro.',
  },
  {
    key: 'profile',
    short: 'PR',
    label: 'Perfil',
    description: 'Emails vinculados e configuracao do GitHub',
    eyebrow: 'Perfil',
    title: 'Identidade e configuracoes',
    descriptionLong: 'Centralize emails vinculados, email padrao e configuracao do GitHub em um unico lugar.',
  },
]
