export const navigationItems = [
  {
    key: 'dashboard',
    short: 'DB',
    label: 'Dashboard',
    labelKey: 'navigation.items.dashboard.label',
    eyebrow: '',
    eyebrowKey: 'navigation.items.dashboard.eyebrow',
    title: 'Dashboard',
    titleKey: 'navigation.items.dashboard.title',
  },
  {
    key: 'tasks',
    short: 'TF',
    label: 'Tarefas',
    labelKey: 'navigation.items.tasks.label',
    eyebrow: 'Issues do GitHub',
    eyebrowKey: 'navigation.items.tasks.eyebrow',
    title: 'Inbox operacional do OctoFlow',
    titleKey: 'navigation.items.tasks.title',
  },
  // {
  //   key: 'test',
  //   short: 'TS',
  //   label: 'Teste',
  //   eyebrow: 'Debug',
  //   title: 'POST de teste para backend',
  // },
  {
    key: 'finance',
    short: 'FN',
    label: 'Financeiro',
    labelKey: 'navigation.items.finance.label',
    eyebrow: 'Financeiro',
    eyebrowKey: 'navigation.items.finance.eyebrow',
    title: 'Controle financeiro pessoal',
    titleKey: 'navigation.items.finance.title',
  },
  {
    key: 'profile',
    short: 'PR',
    label: 'Perfil',
    labelKey: 'navigation.items.profile.label',
    eyebrow: 'Perfil',
    eyebrowKey: 'navigation.items.profile.eyebrow',
    title: 'Identidade e configuracoes',
    titleKey: 'navigation.items.profile.title',
  },
]
