export const updateTemplates = [
  {
    key: 'status-update',
    label: 'Atualizacao de status',
    description: 'Resumo rapido do andamento atual do chamado.',
    markdownTitle: 'Atualizacao de status',
    fields: [
      {
        key: 'date',
        label: 'Data',
        type: 'text',
        renderAs: 'bullet',
        defaultValue: () => new Date().toLocaleString('pt-BR'),
      },
      {
        key: 'owner',
        label: 'Responsavel',
        type: 'text',
        renderAs: 'bullet',
        placeholder: 'Quem esta conduzindo o atendimento',
      },
      {
        key: 'commitRef',
        label: 'Commit relacionado',
        type: 'text',
        renderAs: 'commit',
        placeholder: 'Hash, SHA curto ou URL do commit',
      },
      {
        key: 'currentStatus',
        label: 'Situacao atual',
        type: 'textarea',
        placeholder: 'Descreva o estado atual do chamado.',
      },
      {
        key: 'nextStep',
        label: 'Proximo passo',
        type: 'textarea',
        placeholder: 'Informe a proxima acao prevista.',
      },
      {
        key: 'notes',
        label: 'Observacoes',
        type: 'textarea',
        placeholder: 'Riscos, alinhamentos ou contexto adicional.',
      },
    ],
  },
  {
    key: 'blocker-update',
    label: 'Bloqueio',
    description: 'Padrao para registrar impedimento e acao necessaria.',
    markdownTitle: 'Bloqueio',
    fields: [
      {
        key: 'date',
        label: 'Data',
        type: 'text',
        renderAs: 'bullet',
        defaultValue: () => new Date().toLocaleString('pt-BR'),
      },
      {
        key: 'owner',
        label: 'Responsavel',
        type: 'text',
        renderAs: 'bullet',
        placeholder: 'Quem esta sinalizando o bloqueio',
      },
      {
        key: 'commitRef',
        label: 'Commit relacionado',
        type: 'text',
        renderAs: 'commit',
        placeholder: 'Hash, SHA curto ou URL do commit',
      },
      {
        key: 'blocker',
        label: 'Bloqueio identificado',
        type: 'textarea',
        placeholder: 'Explique claramente o impedimento.',
      },
      {
        key: 'impact',
        label: 'Impacto',
        type: 'textarea',
        placeholder: 'O que esta sendo afetado por este bloqueio.',
      },
      {
        key: 'requiredAction',
        label: 'Acao necessaria',
        type: 'textarea',
        placeholder: 'O que precisa acontecer para liberar o fluxo.',
      },
    ],
  },
  {
    key: 'handoff-update',
    label: 'Repasse',
    description: 'Contexto pronto para troca de responsavel.',
    markdownTitle: 'Repasse de atendimento',
    fields: [
      {
        key: 'date',
        label: 'Data',
        type: 'text',
        renderAs: 'bullet',
        defaultValue: () => new Date().toLocaleString('pt-BR'),
      },
      {
        key: 'nextOwner',
        label: 'Proximo responsavel',
        type: 'text',
        renderAs: 'bullet',
        placeholder: 'Pessoa ou time que assume a issue',
      },
      {
        key: 'commitRef',
        label: 'Commit relacionado',
        type: 'text',
        renderAs: 'commit',
        placeholder: 'Hash, SHA curto ou URL do commit',
      },
      {
        key: 'currentContext',
        label: 'Contexto atual',
        type: 'textarea',
        placeholder: 'Resumo do que ja foi feito e da situacao atual.',
      },
      {
        key: 'doneItems',
        label: 'Itens concluidos',
        type: 'list',
        listStyle: 'bullet',
        placeholder: 'Um item por linha.',
      },
      {
        key: 'pendingItems',
        label: 'Pendencias',
        type: 'list',
        listStyle: 'checklist',
        placeholder: 'Uma pendencia por linha.',
      },
    ],
  },
  {
    key: 'resolution-update',
    label: 'Resolucao',
    description: 'Fechamento estruturado do chamado.',
    markdownTitle: 'Resolucao do chamado',
    fields: [
      {
        key: 'date',
        label: 'Data',
        type: 'text',
        renderAs: 'bullet',
        defaultValue: () => new Date().toLocaleString('pt-BR'),
      },
      {
        key: 'owner',
        label: 'Responsavel',
        type: 'text',
        renderAs: 'bullet',
        placeholder: 'Quem aplicou a correcao',
      },
      {
        key: 'commitRef',
        label: 'Commit relacionado',
        type: 'text',
        renderAs: 'commit',
        placeholder: 'Hash, SHA curto ou URL do commit',
      },
      {
        key: 'rootCause',
        label: 'Causa raiz',
        type: 'textarea',
        placeholder: 'Descreva a origem do problema.',
      },
      {
        key: 'appliedFix',
        label: 'Ajuste aplicado',
        type: 'textarea',
        placeholder: 'Explique a mudanca realizada.',
      },
      {
        key: 'validation',
        label: 'Validacao realizada',
        type: 'list',
        listStyle: 'checklist',
        placeholder: 'Um teste ou validacao por linha.',
      },
      {
        key: 'followUp',
        label: 'Acompanhamentos',
        type: 'list',
        listStyle: 'bullet',
        placeholder: 'Itens adicionais ou monitoramentos futuros.',
      },
    ],
  },
]
